/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VenderRouteImport } from './routes/vender'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventosIndexRouteImport } from './routes/eventos.index'
import { Route as CursosIndexRouteImport } from './routes/cursos.index'
import { Route as VerificarIngressoCodeRouteImport } from './routes/verificar-ingresso.$code'
import { Route as EventosSlugRouteImport } from './routes/eventos.$slug'
import { Route as CursosSlugRouteImport } from './routes/cursos.$slug'
import { Route as AuthenticatedProdutorRouteImport } from './routes/_authenticated/produtor'
import { Route as AuthenticatedMinhasComprasRouteImport } from './routes/_authenticated/minhas-compras'
import { Route as AuthenticatedCheckinRouteImport } from './routes/_authenticated/checkin'
import { Route as AuthenticatedAdminPagamentosRouteImport } from './routes/_authenticated/admin-pagamentos'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedProdutorIndexRouteImport } from './routes/_authenticated/produtor.index'
import { Route as AuthenticatedProdutorEventosRouteImport } from './routes/_authenticated/produtor.eventos'
import { Route as AuthenticatedProdutorCursosRouteImport } from './routes/_authenticated/produtor.cursos'
import { Route as AuthenticatedCheckoutOrderIdRouteImport } from './routes/_authenticated/checkout.$orderId'
import { Route as ApiPublicWebhooksMercadopagoRouteImport } from './routes/api/public/webhooks/mercadopago'
import { Route as ApiInternalReconcileMercadopagoRouteImport } from './routes/api/internal/reconcile/mercadopago'

const VenderRoute = VenderRouteImport.update({
  id: '/vender',
  path: '/vender',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosIndexRoute = EventosIndexRouteImport.update({
  id: '/eventos/',
  path: '/eventos/',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosIndexRoute = CursosIndexRouteImport.update({
  id: '/cursos/',
  path: '/cursos/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificarIngressoCodeRoute = VerificarIngressoCodeRouteImport.update({
  id: '/verificar-ingresso/$code',
  path: '/verificar-ingresso/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosSlugRoute = EventosSlugRouteImport.update({
  id: '/eventos/$slug',
  path: '/eventos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosSlugRoute = CursosSlugRouteImport.update({
  id: '/cursos/$slug',
  path: '/cursos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProdutorRoute = AuthenticatedProdutorRouteImport.update({
  id: '/produtor',
  path: '/produtor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMinhasComprasRoute =
  AuthenticatedMinhasComprasRouteImport.update({
    id: '/minhas-compras',
    path: '/minhas-compras',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCheckinRoute = AuthenticatedCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminPagamentosRoute =
  AuthenticatedAdminPagamentosRouteImport.update({
    id: '/admin-pagamentos',
    path: '/admin-pagamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProdutorIndexRoute =
  AuthenticatedProdutorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProdutorRoute,
  } as any)
const AuthenticatedProdutorEventosRoute =
  AuthenticatedProdutorEventosRouteImport.update({
    id: '/eventos',
    path: '/eventos',
    getParentRoute: () => AuthenticatedProdutorRoute,
  } as any)
const AuthenticatedProdutorCursosRoute =
  AuthenticatedProdutorCursosRouteImport.update({
    id: '/cursos',
    path: '/cursos',
    getParentRoute: () => AuthenticatedProdutorRoute,
  } as any)
const AuthenticatedCheckoutOrderIdRoute =
  AuthenticatedCheckoutOrderIdRouteImport.update({
    id: '/checkout/$orderId',
    path: '/checkout/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicWebhooksMercadopagoRoute =
  ApiPublicWebhooksMercadopagoRouteImport.update({
    id: '/api/public/webhooks/mercadopago',
    path: '/api/public/webhooks/mercadopago',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalReconcileMercadopagoRoute =
  ApiInternalReconcileMercadopagoRouteImport.update({
    id: '/api/internal/reconcile/mercadopago',
    path: '/api/internal/reconcile/mercadopago',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/vender': typeof VenderRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin-pagamentos': typeof AuthenticatedAdminPagamentosRoute
  '/checkin': typeof AuthenticatedCheckinRoute
  '/minhas-compras': typeof AuthenticatedMinhasComprasRoute
  '/produtor': typeof AuthenticatedProdutorRouteWithChildren
  '/cursos/$slug': typeof CursosSlugRoute
  '/eventos/$slug': typeof EventosSlugRoute
  '/verificar-ingresso/$code': typeof VerificarIngressoCodeRoute
  '/cursos/': typeof CursosIndexRoute
  '/eventos/': typeof EventosIndexRoute
  '/checkout/$orderId': typeof AuthenticatedCheckoutOrderIdRoute
  '/produtor/cursos': typeof AuthenticatedProdutorCursosRoute
  '/produtor/eventos': typeof AuthenticatedProdutorEventosRoute
  '/produtor/': typeof AuthenticatedProdutorIndexRoute
  '/api/internal/reconcile/mercadopago': typeof ApiInternalReconcileMercadopagoRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/vender': typeof VenderRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin-pagamentos': typeof AuthenticatedAdminPagamentosRoute
  '/checkin': typeof AuthenticatedCheckinRoute
  '/minhas-compras': typeof AuthenticatedMinhasComprasRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/eventos/$slug': typeof EventosSlugRoute
  '/verificar-ingresso/$code': typeof VerificarIngressoCodeRoute
  '/cursos': typeof CursosIndexRoute
  '/eventos': typeof EventosIndexRoute
  '/checkout/$orderId': typeof AuthenticatedCheckoutOrderIdRoute
  '/produtor/cursos': typeof AuthenticatedProdutorCursosRoute
  '/produtor/eventos': typeof AuthenticatedProdutorEventosRoute
  '/produtor': typeof AuthenticatedProdutorIndexRoute
  '/api/internal/reconcile/mercadopago': typeof ApiInternalReconcileMercadopagoRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/vender': typeof VenderRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/admin-pagamentos': typeof AuthenticatedAdminPagamentosRoute
  '/_authenticated/checkin': typeof AuthenticatedCheckinRoute
  '/_authenticated/minhas-compras': typeof AuthenticatedMinhasComprasRoute
  '/_authenticated/produtor': typeof AuthenticatedProdutorRouteWithChildren
  '/cursos/$slug': typeof CursosSlugRoute
  '/eventos/$slug': typeof EventosSlugRoute
  '/verificar-ingresso/$code': typeof VerificarIngressoCodeRoute
  '/cursos/': typeof CursosIndexRoute
  '/eventos/': typeof EventosIndexRoute
  '/_authenticated/checkout/$orderId': typeof AuthenticatedCheckoutOrderIdRoute
  '/_authenticated/produtor/cursos': typeof AuthenticatedProdutorCursosRoute
  '/_authenticated/produtor/eventos': typeof AuthenticatedProdutorEventosRoute
  '/_authenticated/produtor/': typeof AuthenticatedProdutorIndexRoute
  '/api/internal/reconcile/mercadopago': typeof ApiInternalReconcileMercadopagoRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacidade'
    | '/sitemap.xml'
    | '/termos'
    | '/vender'
    | '/admin'
    | '/admin-pagamentos'
    | '/checkin'
    | '/minhas-compras'
    | '/produtor'
    | '/cursos/$slug'
    | '/eventos/$slug'
    | '/verificar-ingresso/$code'
    | '/cursos/'
    | '/eventos/'
    | '/checkout/$orderId'
    | '/produtor/cursos'
    | '/produtor/eventos'
    | '/produtor/'
    | '/api/internal/reconcile/mercadopago'
    | '/api/public/webhooks/mercadopago'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacidade'
    | '/sitemap.xml'
    | '/termos'
    | '/vender'
    | '/admin'
    | '/admin-pagamentos'
    | '/checkin'
    | '/minhas-compras'
    | '/cursos/$slug'
    | '/eventos/$slug'
    | '/verificar-ingresso/$code'
    | '/cursos'
    | '/eventos'
    | '/checkout/$orderId'
    | '/produtor/cursos'
    | '/produtor/eventos'
    | '/produtor'
    | '/api/internal/reconcile/mercadopago'
    | '/api/public/webhooks/mercadopago'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/privacidade'
    | '/sitemap.xml'
    | '/termos'
    | '/vender'
    | '/_authenticated/admin'
    | '/_authenticated/admin-pagamentos'
    | '/_authenticated/checkin'
    | '/_authenticated/minhas-compras'
    | '/_authenticated/produtor'
    | '/cursos/$slug'
    | '/eventos/$slug'
    | '/verificar-ingresso/$code'
    | '/cursos/'
    | '/eventos/'
    | '/_authenticated/checkout/$orderId'
    | '/_authenticated/produtor/cursos'
    | '/_authenticated/produtor/eventos'
    | '/_authenticated/produtor/'
    | '/api/internal/reconcile/mercadopago'
    | '/api/public/webhooks/mercadopago'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermosRoute: typeof TermosRoute
  VenderRoute: typeof VenderRoute
  CursosSlugRoute: typeof CursosSlugRoute
  EventosSlugRoute: typeof EventosSlugRoute
  VerificarIngressoCodeRoute: typeof VerificarIngressoCodeRoute
  CursosIndexRoute: typeof CursosIndexRoute
  EventosIndexRoute: typeof EventosIndexRoute
  ApiInternalReconcileMercadopagoRoute: typeof ApiInternalReconcileMercadopagoRoute
  ApiPublicWebhooksMercadopagoRoute: typeof ApiPublicWebhooksMercadopagoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vender': {
      id: '/vender'
      path: '/vender'
      fullPath: '/vender'
      preLoaderRoute: typeof VenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/': {
      id: '/eventos/'
      path: '/eventos'
      fullPath: '/eventos/'
      preLoaderRoute: typeof EventosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/': {
      id: '/cursos/'
      path: '/cursos'
      fullPath: '/cursos/'
      preLoaderRoute: typeof CursosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verificar-ingresso/$code': {
      id: '/verificar-ingresso/$code'
      path: '/verificar-ingresso/$code'
      fullPath: '/verificar-ingresso/$code'
      preLoaderRoute: typeof VerificarIngressoCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/$slug': {
      id: '/eventos/$slug'
      path: '/eventos/$slug'
      fullPath: '/eventos/$slug'
      preLoaderRoute: typeof EventosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/$slug': {
      id: '/cursos/$slug'
      path: '/cursos/$slug'
      fullPath: '/cursos/$slug'
      preLoaderRoute: typeof CursosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/produtor': {
      id: '/_authenticated/produtor'
      path: '/produtor'
      fullPath: '/produtor'
      preLoaderRoute: typeof AuthenticatedProdutorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minhas-compras': {
      id: '/_authenticated/minhas-compras'
      path: '/minhas-compras'
      fullPath: '/minhas-compras'
      preLoaderRoute: typeof AuthenticatedMinhasComprasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkin': {
      id: '/_authenticated/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof AuthenticatedCheckinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-pagamentos': {
      id: '/_authenticated/admin-pagamentos'
      path: '/admin-pagamentos'
      fullPath: '/admin-pagamentos'
      preLoaderRoute: typeof AuthenticatedAdminPagamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtor/': {
      id: '/_authenticated/produtor/'
      path: '/'
      fullPath: '/produtor/'
      preLoaderRoute: typeof AuthenticatedProdutorIndexRouteImport
      parentRoute: typeof AuthenticatedProdutorRoute
    }
    '/_authenticated/produtor/eventos': {
      id: '/_authenticated/produtor/eventos'
      path: '/eventos'
      fullPath: '/produtor/eventos'
      preLoaderRoute: typeof AuthenticatedProdutorEventosRouteImport
      parentRoute: typeof AuthenticatedProdutorRoute
    }
    '/_authenticated/produtor/cursos': {
      id: '/_authenticated/produtor/cursos'
      path: '/cursos'
      fullPath: '/produtor/cursos'
      preLoaderRoute: typeof AuthenticatedProdutorCursosRouteImport
      parentRoute: typeof AuthenticatedProdutorRoute
    }
    '/_authenticated/checkout/$orderId': {
      id: '/_authenticated/checkout/$orderId'
      path: '/checkout/$orderId'
      fullPath: '/checkout/$orderId'
      preLoaderRoute: typeof AuthenticatedCheckoutOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/webhooks/mercadopago': {
      id: '/api/public/webhooks/mercadopago'
      path: '/api/public/webhooks/mercadopago'
      fullPath: '/api/public/webhooks/mercadopago'
      preLoaderRoute: typeof ApiPublicWebhooksMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/reconcile/mercadopago': {
      id: '/api/internal/reconcile/mercadopago'
      path: '/api/internal/reconcile/mercadopago'
      fullPath: '/api/internal/reconcile/mercadopago'
      preLoaderRoute: typeof ApiInternalReconcileMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedProdutorRouteChildren {
  AuthenticatedProdutorCursosRoute: typeof AuthenticatedProdutorCursosRoute
  AuthenticatedProdutorEventosRoute: typeof AuthenticatedProdutorEventosRoute
  AuthenticatedProdutorIndexRoute: typeof AuthenticatedProdutorIndexRoute
}

const AuthenticatedProdutorRouteChildren: AuthenticatedProdutorRouteChildren = {
  AuthenticatedProdutorCursosRoute: AuthenticatedProdutorCursosRoute,
  AuthenticatedProdutorEventosRoute: AuthenticatedProdutorEventosRoute,
  AuthenticatedProdutorIndexRoute: AuthenticatedProdutorIndexRoute,
}

const AuthenticatedProdutorRouteWithChildren =
  AuthenticatedProdutorRoute._addFileChildren(
    AuthenticatedProdutorRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAdminPagamentosRoute: typeof AuthenticatedAdminPagamentosRoute
  AuthenticatedCheckinRoute: typeof AuthenticatedCheckinRoute
  AuthenticatedMinhasComprasRoute: typeof AuthenticatedMinhasComprasRoute
  AuthenticatedProdutorRoute: typeof AuthenticatedProdutorRouteWithChildren
  AuthenticatedCheckoutOrderIdRoute: typeof AuthenticatedCheckoutOrderIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAdminPagamentosRoute: AuthenticatedAdminPagamentosRoute,
  AuthenticatedCheckinRoute: AuthenticatedCheckinRoute,
  AuthenticatedMinhasComprasRoute: AuthenticatedMinhasComprasRoute,
  AuthenticatedProdutorRoute: AuthenticatedProdutorRouteWithChildren,
  AuthenticatedCheckoutOrderIdRoute: AuthenticatedCheckoutOrderIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermosRoute: TermosRoute,
  VenderRoute: VenderRoute,
  CursosSlugRoute: CursosSlugRoute,
  EventosSlugRoute: EventosSlugRoute,
  VerificarIngressoCodeRoute: VerificarIngressoCodeRoute,
  CursosIndexRoute: CursosIndexRoute,
  EventosIndexRoute: EventosIndexRoute,
  ApiInternalReconcileMercadopagoRoute: ApiInternalReconcileMercadopagoRoute,
  ApiPublicWebhooksMercadopagoRoute: ApiPublicWebhooksMercadopagoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
